# Importing

In [1]:
import numpy as np

# Set up of equations

## equation 1

* p = scalar to make sure that ti is always unit length
* b = determines the speed of drift (how much does a new input change the overall context)
* pre_ti = previous context
* ti_IN = context of the current item

In [2]:
# Equation 1
def calc_ti(p, b, pre_ti, ti_IN):
    ti = (p * pre_ti) + (b * ti_IN)
    return ti

## equation 2

* M_FT = item to context matrix (represents knowledge)
* fi = item vector

In [3]:
# Equation 2
def calc_t_in_i(M_FT, fi):
    non_normal_t_in_i = np.dot(M_FT, fi) # add current item to previous context
    t_in_i_norm = np.linalg.norm(non_normal_t_in_i) # get the norm of the vector
    t_in_i = non_normal_t_in_i / t_in_i_norm # normalize the vector
    return t_in_i

## equation 3

* y = weighting of learned knowledge vs previous knowledge
* M_FT_pre = knowledge of the item/context known before experiment
* M_FT_exp = knowledge of the item/context connection learned during experiment

In [4]:
# Equation 3
def calc_M_FT(y, M_FT_pre, M_FT_exp):
    M_FT = (1 - y) * M_FT_pre + y * M_FT_exp
    return M_FT

## equation 4

* M_FT_exp = knowledge of the item/context connection learned during experiment
* pre_ti = previous context
* fi = item vector

In [5]:
# Equation 4 + some guess
def calc_M_FT_exp(M_FT_exp, pre_ti, fi):
    delt_M_FT_exp = np.dot(pre_ti, fi.transpose()) # Equation 4
    M_FT_exp = M_FT_exp + delt_M_FT_exp # educated guess
    return M_FT_exp
    

# Initiate starting state

## Sizes of items

*the following feels all wrong*

t will be a vector with shape m x p. it will show how much each context was activated for each feature of f.

f will be an item vector with shape n x p. p is the number of different item context relationships. If p is 1 (which it will be in our case) it is a single item. if p>1 then it could be thought of as multiple items and the contexts they each bring up. p is also the number of features of each item ?

M_FT will be a matrix with shape m x n (rows[m] represent reatures of contexts; columns[n] represent features of items). Such that reading a row tells you what items a single context is realted to, reading a column tells you what contexts a single item activates

## Starting numbers

In [6]:
p = .5  # I have no idea how to manipulate p such that length of ti = 1
        # After doing some math I think I may need assitance with this... 

b = .8  # This is just set to be whatever you want

pre_ti = np.array([0,0,0,0,0])

y = .5  # This is just set to be whatever 

M_FT_pre = np.identity(5) # this needs to match the size of something?
M_FT_exp = np.zeros((5,5)) # this needs to match the shape of MFTPre


# Calculate by hand

I'll go step by step to calculate each iteration as shown in this picture
![TCM-A_byHand](tcm-a_byHand.jpg)

## i = 1

In [7]:
# 1)
f1 = np.array([1,0,0,0,0])
print(f1)

[1 0 0 0 0]


In [8]:
# 2
M_FT = calc_M_FT(y, M_FT_pre, M_FT_exp)
t1_IN = calc_t_in_i(M_FT, f1)
print(t1_IN)

[1. 0. 0. 0. 0.]


In [9]:
# 3
M_FT_exp = calc_M_FT_exp(M_FT_exp, pre_ti, f1)
print(M_FT_exp)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
# 4
t1 = calc_ti(p, b, pre_ti, t1_IN)
print(t1)

[0.8 0.  0.  0.  0. ]


## i = 2

In [11]:
pre_ti = t1

In [12]:
# 1)
f2 = np.array([0,1,0,0,0])
print(f2)

[0 1 0 0 0]


In [13]:
# 2
M_FT = calc_M_FT(y, M_FT_pre, M_FT_exp)
t2_IN = calc_t_in_i(M_FT, f2)
print(t2_IN)

[0. 1. 0. 0. 0.]


In [14]:
# 3
M_FT_exp = calc_M_FT_exp(M_FT_exp, pre_ti, f2)
print(M_FT_exp)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
# 4
t2 = calc_ti(p, b, pre_ti, t2_IN)
print(t2)

[0.4 0.8 0.  0.  0. ]
