# Importing

In [1]:
import numpy as np

# Set up of equations

## equation 1

* p = scalar to make sure that ti is always unit length
* b = determines the speed of drift (how much does a new input change the overall context)
* pre_ti = previous context
* ti_IN = context of the current item

In [2]:
# Equation 1
def calc_ti(p, b, pre_ti, ti_IN):
    ti = (p * pre_ti) + (b * ti_IN)
    return ti

## equation 2

* M_FT = item to context matrix (represents knowledge)
* fi = item vector

In [3]:
# Equation 2
def calc_t_in_i(M_FT, fi):
    non_normal_t_in_i = np.dot(M_FT, fi) # add current item to previous context
    t_in_i_norm = np.linalg.norm(non_normal_t_in_i) # get the norm of the vector
    t_in_i = non_normal_t_in_i / t_in_i_norm # normalize the vector
    return t_in_i

## equation 3

* y = weighting of learned knowledge vs previous knowledge
* M_FT_pre = knowledge of the item/context known before experiment
* M_FT_exp = knowledge of the item/context connection learned during experiment

In [4]:
# Equation 3
def calc_M_FT(y, M_FT_pre, M_FT_exp):
    M_FT = (1 - y) * M_FT_pre + y * M_FT_exp
    return M_FT

## equation 4

* M_FT_exp = knowledge of the item/context connection learned during experiment
* pre_ti = previous context
* fi = item vector

In [5]:
# Equation 4 + some guess
def calc_M_FT_exp(M_FT_exp, pre_ti, fi):
    #print("pre_ti", pre_ti)
    #print("fi", fi)
    # delt_M_FT_exp = np.dot(pre_ti, fi) # Equation 4
    delt_M_FT_exp = np.outer(pre_ti,fi) # Equation 4 ? Still unclear on the how np does dot vs outer with vectors
    #print("delt \n", delt_M_FT_exp)
    #print()
    M_FT_exp = M_FT_exp + delt_M_FT_exp # educated guess
    return M_FT_exp
    

# Initiate starting state

## Sizes of items

*the following feels all wrong*

t will be a vector with shape m x p. it will show how much each context was activated for each feature of f.

f will be an item vector with shape n x p. p is the number of different item context relationships. If p is 1 (which it will be in our case) it is a single item. if p>1 then it could be thought of as multiple items and the contexts they each bring up. p is also the number of features of each item ?

M_FT will be a matrix with shape m x n (rows[m] represent reatures of contexts; columns[n] represent features of items). Such that reading a row tells you what items a single context is realted to, reading a column tells you what contexts a single item activates

## Starting numbers

In [6]:
p = .5  # I have no idea how to manipulate p such that length of ti = 1
        # After doing some math I think I may need assitance with this... 

b = .8  # This is just set to be whatever you want

pre_ti = np.array([0,0,0,0,0])

y = .5  # This is just set to be whatever 

M_FT_pre = np.identity(5) # this needs to match the size of something?
M_FT_exp = np.zeros((5,5)) # this needs to match the shape of MFTPre


# Calculate by hand

I'll go step by step to calculate each iteration as shown in this picture
![TCM-A_byHand](tcm-a_byHand.jpg)

## i = 1

In [7]:
# 1)
f1 = np.array([1,0,0,0,0])
print(f1)

[1 0 0 0 0]


In [8]:
# 2
M_FT = calc_M_FT(y, M_FT_pre, M_FT_exp)
t1_IN = calc_t_in_i(M_FT, f1)
print(t1_IN)

[1. 0. 0. 0. 0.]


In [9]:
# 3
M_FT_exp = calc_M_FT_exp(M_FT_exp, pre_ti, f1)
print(M_FT_exp)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


This shows that after the presentation of the first item there is no association between items. (There aren't any items to associate)

In [10]:
# 4
t1 = calc_ti(p, b, pre_ti, t1_IN)
print(t1)

[0.8 0.  0.  0.  0. ]


## i = 2

In [11]:
pre_ti = t1

In [12]:
# 1)
f2 = np.array([0,1,0,0,0])
print(f2)

[0 1 0 0 0]


In [13]:
# 2
M_FT = calc_M_FT(y, M_FT_pre, M_FT_exp)
t2_IN = calc_t_in_i(M_FT, f2)
print(t2_IN)

[0. 1. 0. 0. 0.]


In [14]:
# 3
M_FT_exp = calc_M_FT_exp(M_FT_exp, pre_ti, f2)
print(M_FT_exp)

[[0.  0.8 0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]]


Here we see that the first item has been bound to the second item. So if presented with the first context, (first row), we will have some binding of the second item. 

In [15]:
# 4
t2 = calc_ti(p, b, pre_ti, t2_IN)
print(t2)

[0.4 0.8 0.  0.  0. ]


## i = 3

In [16]:
pre_ti = t2

In [17]:
# 1)
f3 = np.array([0,0,1,0,0])
print(f3)

[0 0 1 0 0]


In [18]:
# 2
M_FT = calc_M_FT(y, M_FT_pre, M_FT_exp)
t3_IN = calc_t_in_i(M_FT, f3)
print(t3_IN)

[0. 0. 1. 0. 0.]


In [19]:
# 3
M_FT_exp = calc_M_FT_exp(M_FT_exp, pre_ti, f3)
print(M_FT_exp)

[[0.  0.8 0.4 0.  0. ]
 [0.  0.  0.8 0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]]


Now, the first context has been bound to the second item and weakly to the third item. The second context has only been bound to the third item.

The columns are the state of the world when that item was presented. The rows are the learned feature associations. So context 1 is associated with features that came later, but not bound by the feature before. 

In [20]:
# 4
t3 = calc_ti(p, b, pre_ti, t3_IN)
print(t3)

[0.2 0.4 0.8 0.  0. ]


# Loop through set of items

## Items

In [21]:
context_vector_shape = 5

In [22]:
F_simple = np.eye(context_vector_shape, context_vector_shape)
F_rand = np.random.rand(context_vector_shape,context_vector_shape)
F = F_simple # np.vstack((F_simple, F_rand))
#print(F)

## initial parameters (copied from above)

In [23]:
p = .5  # I have no idea how to manipulate p such that length of ti = 1
        # After doing some math I think I may need assitance with this... 

b = .9  # This is just set to be whatever you want

ti = np.zeros((1,context_vector_shape))
T = ti # T is the set of contexts

y = .5  # This is just set to be whatever 

M_FT_pre = np.identity(context_vector_shape) # this needs to match the size of something?
M_FT_exp = np.zeros((context_vector_shape,context_vector_shape)) # this needs to match the shape of MFTPre


## Iterate through the items

In [24]:
for i in range(len(F)):
    # the numbers match the steps from the blackboard
    #print("Iteration =", i)
    # 1
    fi = F[i]
    #print("f=", fi)
    # Set previous context
    pre_ti = ti
    
    # start loop
    # 2
    M_FT = calc_M_FT(y, M_FT_pre, M_FT_exp)
    ti_IN = calc_t_in_i(M_FT, fi)
    
    # 3
    M_FT_exp = calc_M_FT_exp(M_FT_exp, pre_ti, fi)
    
    # 4
    ti = calc_ti(p, b, pre_ti, ti_IN)
    #print("The new context is: ", ti)
    
    T = np.vstack((T,ti))
    

In [25]:
print("History of the context.")
print("\t Top row is earliest")    
print(T)

print()
print("Current Item to context association.")
print("\t Column = context of that item presented")
print("\t Row = Features \"bound\" to that context")
print()
print(M_FT_exp)

History of the context.
	 Top row is earliest
[[0.      0.      0.      0.      0.     ]
 [0.9     0.      0.      0.      0.     ]
 [0.45    0.9     0.      0.      0.     ]
 [0.225   0.45    0.9     0.      0.     ]
 [0.1125  0.225   0.45    0.9     0.     ]
 [0.05625 0.1125  0.225   0.45    0.9    ]]

Current Item to context association.
	 Column = context of that item presented
	 Row = Features "bound" to that context

[[0.     0.9    0.45   0.225  0.1125]
 [0.     0.     0.9    0.45   0.225 ]
 [0.     0.     0.     0.9    0.45  ]
 [0.     0.     0.     0.     0.9   ]
 [0.     0.     0.     0.     0.    ]]
